### ISSUE TITLE
password update reminder breaks the s30 sign-in for http://ftlabs-screens.herokuapp.com/admin on mobile

### ISSUE THREAD

**Issue by railsagainstignorance** [Financial-Times/s3o-middleware#14]
Hi,

when trying to access the s3o-protected admin page of screens, http://ftlabs-screens.herokuapp.com/admin, on my Nexus 4 android phone, I hit problems when the s3o page reminds me of a not-very-imminent password change and requires me to ok the reminder. I then get told I need to authenticate to get to the admin page. Refreshing the page fails, presumably because the session guff in the url is corrupt. The only way to progress is to go back to the initial url and try again (having ticked the do not remind me again box in the s3o password reminder page beforehand).

So, yeah. There you go

-Chris.

**Comment by matthew-andrews** [comment]
is this an issue with the middleware or s3o itself?
