### ISSUE TITLE
Drops some query strings

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/s3o-middleware#15]
e.g. http://ft-next-beacon-v2.herokuapp.com/data/query-wizard?query=@concat(cta:click-%3Ecount()-%3Efilter(context.domPath~follow-promo-header),cta:click-%3Ecount()-%3Efilter(context.domPath~suggested-article),cta:click-%3Ecount()-%3Efilter(context.domPath~section-link),cta:click-%3Ecount()-%3Efilter(context.domPath~next-up-header),)-%3Efilter(page.location.type=article)-%3ErelTime(1)

**Comment by wheresrhys** [comment]
Initial investigation suggests it doesn't like it when they begin with an `@`

**Comment by matthew-andrews** [comment]
i think those should probably be better URLs if the `@` were `encodeURIComponent`ed => `%40`.

**Comment by wheresrhys** [comment]
yep, will definitely be doing that, but thought I'd report as maybe s3o should attempt to handle this scenario. There are lots of other non encoded characters in the url that it does cope with, so its easy for people to think non-uri encoding is ok, but then get caught out by this.

**Comment by JakeChampion** [comment]
I don't think S3O should deal with this, it is a simple piece of middleware that does one job, ExpressJS handles the URL parsing for us.
