### ISSUE TITLE
auth cookies not set by the time client side requests are sent from authenticated page

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/s3o-middleware#17]
e.g. on beacon.ft.com auth, after all s3o redirects have occurred for the first page load all fetch request to an api proxy at beacon.ft.com/data/keen-cache fail as they do not appear to have the session cookies set.

**Comment by wheresrhys** [comment]
`{credentials: 'FACEPALM'}`

**Comment by matthew-andrews** [comment]
:)
