### ISSUE TITLE
Don't set cookies unecessarily

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/s3o-middleware#18]
Have had to disable s3o for API calls proxied via next-beacon-v2 because it always sets cookies https://github.com/Financial-Times/s3o-middleware/blob/master/index.js#L29, which means the response is uncachable in varnish

My naive solution would be to check for req.cookie.session_token and username before setting them. Any reason not to do this? 

PS - I'm not 100% sure this is the cause of the problem, but seems quite likely

**Comment by JakeChampion** [comment]
Are you using the non redirecting S3O middleware?

```
var express = require('express');
var app = express();
var router = express.Router();
var authS3ONoRedirect = require('s3o-middleware').authS3ONoRedirect;

app.get('/some-authenticated-api', authS3ONoRedirect, router);
```

**Comment by lucas42** [comment]
I think it's sensible not to set cookies on pages which have been authenticated based on existing cookies.
(Note it's possible to have an existing out-of-date cookie and be authenticated via a redirect from s3o, in which case we *should* set cookies).

Having said that, I'd be very cautious about putting caching in front of authentication.  You'll likely end up with unauthenticated users being able to access cached content.
