### ISSUE TITLE
"cookie-parser" npm module is required

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/S3O-middleware#2]
If I remove the "cookie-parser" module from my app, I receive this error:
```
error: Uncaught Error - TypeError: Cannot read property 's3o_username' of undefined
    at authS3O (/Users/adambraimbridge/Sites/next-beacon-dashboard/node_modules/s3o-middleware/index.js:77:22)
```

**Comment by adambraimbridge** [comment]
I think this may still require one more line of code — maybe ...

`var cookieParser	= require('cookie-parser');`

See: https://github.com/Financial-Times/next-beacon-dashboard/blob/master/server/app.js#L8

**Comment by adambraimbridge** [comment]
Oh, and `app.use(cookieParser());` too? (https://github.com/Financial-Times/next-beacon-dashboard/blob/master/server/app.js#L45)

**Comment by JakeChampion** [comment]
I'm not too sure if we want the middleware to handle parsing of cookies. What do you think about having the readme mention the requirement of `req.cookies` having to exists before using this middleware?

**Comment by JakeChampion** [comment]
We could add a default cookie parser, like so:
```
if (req.cookies === undefined || req.cookies === null) {
		var cookies = req.headers.cookie;
	    if (cookies) {
			req.cookies = cookie.parse(cookies, options);
	    } else {
			req.cookies = Object.create(null);
	    }
	}
```

**Comment by matthew-andrews** [comment]
surely that module does that anyway ^^

**Comment by matthew-andrews** [comment]
yes https://github.com/expressjs/cookie-parser/blob/master/index.js#L25

**Comment by JakeChampion** [comment]
Yes it does, I just don't think middleware can itself consume middleware.

**Comment by adambraimbridge** [comment]
An appropriate note in the readme, like set-up instructions or whatever, would be fine I think.

**Comment by adambraimbridge** [comment]
Update: Brilliant! Thanks -> https://github.com/Financial-Times/S3O-middleware/pull/3/files

**Comment by matthew-andrews** [comment]
> Yes it does, I just don't think middleware can itself consume middleware.

ahh good point

**Comment by JakeChampion** [comment]
Released - https://github.com/Financial-Times/S3O-middleware/releases/tag/1.0.1
