### ISSUE TITLE
Successful authentication shows error screen but works on refresh

### ISSUE THREAD

**Issue by seanmtracey** [Financial-Times/s3o-middleware#22]
## Issue

When trying to authenticate as an FT user, I go through the typical process, but rather than being redirected back to the service I've come from, I get shown the error page despite having what seems to be a valid token in the query parameters

![error](https://cloud.githubusercontent.com/assets/913687/13916452/a1887b5e-ef52-11e5-8c0f-4d69f5651d9e.png)

I notice that the url generated by the middleware has my user name twice, but I can't imagine this would cause a problem.
`?username=sean.tracey&token=[REDACTED]&username=sean.tracey`

**Comment by JakeChampion** [comment]
That shouldn't cause a problem. The token would be valid unless the key changed whilst S3O was handling this request.

**Comment by lucas42** [comment]
I'm not sure there's any advantage in have a code path capable of displaying this error page.  When authentication fails, can't we just redirect back to s3o and start the auth flow again?
